parameters:

services:

  # Core

#  resque:
#    class: Resque

  resque.event_dispatcher:
    class: Resque\Bundle\ResqueBundle\Bridge\EventDispatcher
    arguments:
      - @event_dispatcher

  resque.system: @resque.system.standard

  resque.system.standard:
    class: Resque\Component\System\StandardSystem

  # Commands

  resque.command.job_enqueue:
    class: Resque\Bundle\ResqueBundle\Command\JobEnqueueCommand
    arguments:
      - @resque.queue.registry
      - @resque.queue.factory
    tags:
       - { name: console.command }

  resque.command.queue_delete:
    class: Resque\Bundle\ResqueBundle\Command\QueueDeleteCommand
    arguments:
      - @resque.queue.registry
      - @resque.queue.factory
    tags:
       - { name: console.command }

  resque.command.queue_list:
    class: Resque\Bundle\ResqueBundle\Command\QueueListCommand
    arguments:
      - @resque.queue.registry
    tags:
       - { name: console.command }

  resque.command.worker_list:
    class: Resque\Bundle\ResqueBundle\Command\WorkerListCommand
    arguments:
      - @resque.worker.registry
    tags:
       - { name: console.command }

  # Worker

  resque.worker.registry:
    class: Resque\Component\Worker\Registry\WorkerRegistry
    arguments:
      - @resque.redis.worker_registry_adapter
      - @resque.event_dispatcher
      - @resque.worker.factory

  resque.worker.factory:
    class: Resque\Component\Worker\Factory\WorkerFactory
    arguments:
      - @resque.queue.factory
      - @resque.job.instance_factory
      - @resque.event_dispatcher
      - @resque.system

  # Queue

  resque.queue.registry:
    class: Resque\Component\Queue\Registry\QueueRegistry
    arguments:
      - @resque.event_dispatcher
      - @resque.redis.queue_adapter
      - @resque.queue.factory

  resque.queue.factory:
    class: Resque\Component\Queue\Factory\QueueFactory
    arguments:
      - @resque.redis.queue_storage
      - @resque.event_dispatcher

  # Job

  resque.job.instance_factory: @resque.job.instance_factory.container_aware

  resque.job.instance_factory.simple:
    class: Resque\Component\Job\Factory\JobInstanceFactory

  resque.job.instance_factory.container_aware:
    class: Resque\Bundle\ResqueBundle\Bridge\ContainerAwareJobInstanceFactory
    calls:
      - ['setContainer', [@service_container]]

  # Redis

  resque.redis.client: @resque.redis.predis_bridge

  resque.redis.predis_bridge:
    class: Resque\Redis\Bridge\PredisBridge
    arguments:
      - @resque.redis.predis_client

  resque.redis.predis_client:
    class: Predis\Client
    arguments:
      - ''
      - {'prefix': 'resque:'}

  resque.redis.queue_adapter:
    class: Resque\Redis\RedisQueueRegistryAdapter
    arguments:
      - @resque.redis.client
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  resque.redis.queue_storage:
    class: Resque\Redis\RedisQueueStorage
    arguments:
      - @resque.redis.client

  resque.redis.worker_registry_adapter:
    class: Resque\Redis\RedisWorkerRegistryAdapter
    arguments:
      - @resque.redis.client
